---
blocking_packages:
  - libindi
  - libindi-static
  - libindi-devel
common_packages:
  - python3-libselinux
  - python3-dnf
indi_packages:
  - '@Development tools'
  - git
  - cmake3
  - libnova
  - libnova-devel
  - libusb
  - libusb-devel
  - cfitsio
  - cfitsio-devel
  - cfitsio-static
  - gtest
  - gtest-devel
  - gmock
  - gmock-devel
  - zlib-devel
  - zlib-static
  - libusbx
  - libusbx-devel
  - libcurl-devel
  - gsl-devel
  - libjpeg-turbo
  - libjpeg-turbo-devel
  - fftw3-devel
  - pkgconfig
  - gcc-c++
  - libtheora-devel
  - gmock-devel
  - gtest-devel
  - libev-devel
indi_3rdparty_packages:
  - '@Development tools'
  - git
  - cmake3
  - pkgconfig
  - libftdi-devel
  - LibRaw-devel
  - libgphoto2-devel
  - libtiff-devel
  - gpsd-devel
  - libdc1394-devel
  - ffmpeg-devel
  - fxload
