---

- name: Install EPEL on CentOS
  become: yes
  package:
    name:
      - epel-release
    state: present
  when:
    - ansible_facts['distribution'] == 'CentOS'


- include_tasks: rpmfusion/main.yml


- name: Install indi_3rdparty development packages
  package:
    name: "{{ indi_3rdparty_packages }}"
    state: present
    enablerepo:
      - PowerTools
      - powertools
  become: yes
